# Form implementation generated from reading ui file 'deisgn.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView_4 = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView_4.setGeometry(QtCore.QRect(0, 0, 131, 701))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView_5.setGeometry(QtCore.QRect(290, 140, 311, 191))
        self.graphicsView_5.setAutoFillBackground(False)
        self.graphicsView_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.graphicsView_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.graphicsView_5.setLineWidth(1)
        self.graphicsView_5.setMidLineWidth(1)
        self.graphicsView_5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.graphicsView_5.setViewportUpdateMode(QtWidgets.QGraphicsView.ViewportUpdateMode.SmartViewportUpdate)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.login_text1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.login_text1.setGeometry(QtCore.QRect(410, 160, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.login_text1.setFont(font)
        self.login_text1.setObjectName("login_text1")
        self.login_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.login_input.setGeometry(QtCore.QRect(330, 190, 231, 20))
        self.login_input.setObjectName("login_input")
        self.password_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.password_text.setGeometry(QtCore.QRect(400, 220, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.password_text.setFont(font)
        self.password_text.setObjectName("password_text")
        self.password_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(330, 260, 231, 20))
        self.password_input.setObjectName("password_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_text1.setText(_translate("MainWindow", "Логин"))
        self.password_text.setText(_translate("MainWindow", "Пароль"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())