# Generated by Django 5.2.4 on 2025-08-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_generateddocument_personaldataagreement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generateddocument",
            name="user",
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
